db:
  host: localhost
  user: postgres
  password: postgres
  name: team_messenger
  port: 5432
app:
  port: 8082
keys:
  rotation_interval: "24h"  # Интервал обновления ключей (24 часа)
  # Другие возможные значения: "1h", "12h", "48h", "168h" (неделя)