// API
export {
  chatApi,
  chatRolesApi,
  createChatFormData,
  updateChatFormData,
  createMessageFormData,
  type GetChatResponse,
  type GetChatsResponse,
  type GetMessagesResponse,
  type SendMessageResponse,
  type CreateChatResponse,
  type CreateChatRequest,
  type UpdateChatRequest,
  type GetMessagesParams,
  type SearchMessagesParams,
  type ChangeUserRoleRequest,
  type MyRoleResponse,
  type ChatRoleResponse,
  type SearchMessagesResponse,
  type ChatMemberResponse,
} from './api/chatApi';

// React Query Hooks
export {
  chatKeys,
  chatRolesKeys,
  transformChatResponse,
  useUserChats,
  useChatMessages,
  useChatMessagesInfinite,
  useSearchMessages,
  useMyRoleInChat,
  useChatRoles,
  useChatMembers,
  hasPermission,
  useCreateChat,
  useUpdateChat,
  useDeleteChat,
  useSendMessage,
  useBanUser,
  useChangeUserRole,
  type ChatWithAvatar,
} from './api/queries';

