app:
  name: "notification-service"
  port: 8085
kafka:
  brokers:
    - "localhost:9092"
  group_id: "notification-service"
  topics:
    notifications: "notifications"
    keys: "key_updates"
email:
  smtp_host: "smtp.yandex.ru"
  smtp_port: 587
  username: ""
  password: ""
  from_email: "noreply@teammessenger.com"
  from_name: "TeamMessenger"
  template_path: "./templates" 